service: aws-lambda-dynamodb-swapi
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:378216413421:table/PeopleTable
        - arn:aws:dynamodb:us-west-2:378216413421:table/PlanetsTable

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
  registrarPeople:
    handler: src/registrarPeople.registrarPeople
    events:
      - httpApi:
          path: /registrar/people
          method: post
  registrarPlanets:
    handler: src/registrarPlanets.registrarPlanets
    events:
      - httpApi:
          path: /registrar/planets
          method: post
  listarPeople:
    handler: src/listarPeople.listarPeople
    events:
      - httpApi:
          path: /listar/people
          method: get
  listarStarships:
    handler: src/listarStarships.listarStarships
    events:
      - httpApi:
          path: /listar/starships
          method: get

resources:
  Resources:
    PeopleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PeopleTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    PlanetsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PlanetsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
